<div class="header header-filter" style="background-image: url('/img/bg-recep-ori.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="brand">
                    <h1>Erreur 404</h1>
                    <h3><?= $this->message ?></h3>
                </div>
            </div>
        </div>

    </div>
</div>

<?php if (isset($this->reason) && $this->reason): ?>

    <?php
    $reasonMessage= 'No Reason givent';
    switch ($this->reason) {
        case 'error-controller-cannot-dispatch':
            $reasonMessage = 'The requested controller was unable to dispatch the request.';
            break;
        case 'error-controller-not-found':
            $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
            break;
        case 'error-controller-invalid':
            $reasonMessage = 'The requested controller was not dispatchable.';
            break;
        case 'error-router-no-match':
            $reasonMessage = 'The requested URL could not be matched by routing.';
            break;
        default:
            $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
            break;
    }
    ?>

<?php endif ?>

<div class="main main-raised">
    <div class="section section-basic">
        <div class="container">
            <div class="title">
                <h2><?= $reasonMessage ?></h2>
            </div>

            <div class="row">


                <?php if (isset($this->controller) && $this->controller): ?>

                <dl>
                    <dt>Controller:</dt>
                    <dd><?= $this->escapeHtml($this->controller) ?>
                <?php
                if (isset($this->controller_class)
                    && $this->controller_class
                    && $this->controller_class != $this->controller
                ) {
                    echo '(' . sprintf('resolves to %s', $this->escapeHtml($this->controller_class)) . ')';
                }
                ?>
                </dd>
                </dl>

                <?php endif ?>

                <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

                <?php if(isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)): ?>
                <hr/>
                <h2>Additional information:</h2>
                <h3><?= get_class($this->exception) ?></h3>
                <dl>
                    <dt>File:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
                    </dd>
                    <dt>Message:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?= $this->exception->getMessage() ?></pre>
                    </dd>
                    <dt>Stack trace:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?= $this->exception->getTraceAsString() ?></pre>
                    </dd>
                </dl>
                <?php
                    $e = $this->exception->getPrevious();
                    $icount = 0;
                    if ($e) :
                ?>
                <hr/>
                <h2>Previous exceptions:</h2>
                <ul class="unstyled">
                    <?php while($e) : ?>
                    <li>
                        <h3><?= get_class($e) ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getMessage() ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getTraceAsString() ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                        $e = $e->getPrevious();
                        $icount += 1;
                        if ($icount >=50) {
                            echo "<li>There may be more exceptions, but we have no enough memory to proccess it.</li>";
                            break;
                        }
                        endwhile;
                    ?>
                </ul>
                <?php endif; ?>

                <?php else: ?>

                <h3>No Exception available</h3>

                <?php endif ?>

                <?php endif ?>
            </div>
        </div>
    </div>
</div>