<div class="row">
    <h1><?= $nickname ?></h1>
</div>
<hr>
<div class="row">
    <div class="col-md-12">
        <h2>Solo Statistics</h2>
    </div>
    <div class="col-md-4">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Solo Statistics</h4>
                <p class="card-category">
                    <i class="fa fa-history"></i>
                    <?= $lifeStats->updatedAt ?>
                </p>
            </div>
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <td>Matches</td>
                            <td class="text-right"><i><?= $lifeStats->soloMatches ?></i></td>
                        </tr>
                        <tr>
                            <td>Wins</td>
                            <td class="text-right"><i><?= $lifeStats->soloTop1 ?> </i> <i class="text-muted">(Rank: <?= $lifeStats->rankSoloTop1 ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Kills</td>
                            <td class="text-right"><i><?= $lifeStats->soloKills ?></i> <i class="text-muted">(Rank: <?= $lifeStats->rankSoloKills ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Score</td>
                            <td class="text-right"><i><?= $lifeStats->soloScore ?></i> <i class="text-muted">(Rank: <?= $lifeStats->rankSoloScore ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Top 10</td>
                            <td class="text-right"><i><?= $lifeStats->top10 ?></i></td>
                        </tr>
                        <tr>
                            <td>Top 25</td>
                            <td class="text-right"><i><?= $lifeStats->top25 ?></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card strpied-tabled-with-hover">
            <div class="card-body">
                <div class="stats-chart" data-dates="<?= $soloDate ?>" data-kills="<?= $soloKills ?>" data-score='<?= $soloScore ?>' data-rank-score='<?= $soloRankScore ?>' data-rank-win='<?= $soloRankTop1 ?>'  data-rank-kills='<?= $soloRankKills ?>'></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Duo Statistics</h2>
    </div>
    <div class="col-md-4">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Solo Statistics</h4>
                <p class="card-category">
                    <i class="fa fa-history"></i>
                    <?= $lifeStats->updatedAt ?>
                </p>
            </div>
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <td>Matches</td>
                            <td class="text-right"><i><?= $lifeStats->duoMatches ?></i></td>
                        </tr>
                        <tr>
                            <td>Wins</td>
                            <td class="text-right"><i><?= $lifeStats->duoTop1 ?> </i> <i class="text-muted">(Rank: <?= $lifeStats->rankDuoTop1 ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Kills</td>
                            <td class="text-right"><i><?= $lifeStats->duoKills ?></i> <i class="text-muted">(Rank: <?= $lifeStats->rankDuoKills ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Score</td>
                            <td class="text-right"><i><?= $lifeStats->duoScore ?></i> <i class="text-muted">(Rank: <?= $lifeStats->rankDuoScore ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Top 5</td>
                            <td class="text-right"><i><?= $lifeStats->top5 ?></i></td>
                        </tr>
                        <tr>
                            <td>Top 12</td>
                            <td class="text-right"><i><?= $lifeStats->top12 ?></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card strpied-tabled-with-hover">
            <div class="card-body">
                <div class="stats-chart" data-dates="<?= $soloDate ?>" data-kills="<?= $duoKills ?>" data-score='<?= $duoScore ?>' data-rank-score='<?= $duoRankScore ?>' data-rank-win='<?= $duoRankTop1 ?>'  data-rank-kills='<?= $duoRankKills ?>'></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Squad Statistics</h2>
    </div>
    <div class="col-md-4">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Squad Statistics</h4>
                <p class="card-category">
                    <i class="fa fa-history"></i>
                    <?= $lifeStats->updatedAt ?>
                </p>
            </div>
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <td>Matches</td>
                            <td class="text-right"><i><?= $lifeStats->squadMatches ?></i></td>
                        </tr>
                        <tr>
                            <td>Wins</td>
                            <td class="text-right"><i><?= $lifeStats->squadTop1 ?> </i> <i class="text-muted">(Rank: <?= $lifeStats->rankSquadTop1 ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Kills</td>
                            <td class="text-right"><i><?= $lifeStats->squadKills ?></i> <i class="text-muted">(Rank: <?= $lifeStats->rankSquadKills ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Score</td>
                            <td class="text-right"><i><?= $lifeStats->squadScore ?></i> <i class="text-muted">(Rank: <?= $lifeStats->rankSquadScore ?>)</i></td>
                        </tr>
                        <tr>
                            <td>Top 3</td>
                            <td class="text-right"><i><?= $lifeStats->top3 ?></i></td>
                        </tr>
                        <tr>
                            <td>Top 6</td>
                            <td class="text-right"><i><?= $lifeStats->top6 ?></i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card strpied-tabled-with-hover">
            <div class="card-body">
                <div class="stats-chart" data-dates="<?= $squadDate ?>" data-kills="<?= $squadKills ?>" data-score='<?= $squadScore ?>' data-rank-score='<?= $squadRankScore ?>' data-rank-win='<?= $squadRankTop1 ?>'  data-rank-kills='<?= $squadRankKills ?>'></div>
            </div>
        </div>
    </div>
</div>