<div class="row">
    <div class="col-md-3 text-right">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="pill" href="#pills-solo" role="tab" aria-controls="pills-home" aria-selected="true">Solo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="pill" href="#pills-duo" role="tab" aria-controls="pills-duo" aria-selected="false">Duo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="pill" href="#pills-squad" role="tab" aria-controls="pills-squad" aria-selected="false">Squad</a>
            </li>
        </ul>
    </div>
    <div class="col-md-6">
          <form method="GET" action="/stats">
              <div class="row">
                  <input type="hidden" name="user" value="<?= $nickname ?>">
                  <div class="col-md-5">
                      <input type="text" name="from" class="form-control datepicker-from" placeholder="From">
                  </div>
                  <div class="col-md-5">
                      <input type="text" name="to" class="form-control datepicker-to" placeholder="to">
                  </div>
                  <div class="col-md-2 col-md-offset-1">
                      <button type='submit' class="btn btn-primary btn-fill"><i class="fa fa-search"></i></button>
                  </div>
              </div>
          </form>
    </div>
    <div class="col-md-3">
        <h1 class="text-right"><?= $nickname ?></h1>
    </div>
</div>
<div class="tab-content" id="pills-tabContent">
    <?php foreach (['solo', 'duo', 'squad'] as $category): ?>
      <div class="tab-pane fade show <?= ($category == 'solo') ? 'active': ''; ?>" id="pills-<?= $category ?>" role="tabpanel" aria-labelledby="pills-<?= $category ?>">
          <div class="row">
              <div class="col-md-4">
                  <div class="card strpied-tabled-with-hover">
                      <div class="card-header ">
                          <h4 class="card-title"><?= ucfirst($category) ?> Statistics</h4>
                          <p class="card-category">
                              <i class="fa fa-history"></i>
                              <?= $lifeStats->updatedAt ?>
                          </p>
                      </div>
                      <div class="card-body table-full-width table-responsive">
                          <table class="table table-hover">
                              <tbody>
                                  <tr>
                                      <td>Matches</td>
                                      <td class="text-right"><i><?= $lifeStats->{$category . 'Matches'} ?></i></td>
                                  </tr>
                                  <tr>
                                      <td>Wins</td>
                                      <td class="text-right"><i><?= $lifeStats->{$category . 'Top1'} ?></i></td>
                                  </tr>
                                  <tr>
                                      <td>Kills</td>
                                      <td class="text-right"><i><?= $lifeStats->{$category . 'Kills'} ?></i></td>
                                  </tr>
                                  <tr>
                                      <td>Score</td>
                                      <td class="text-right"><i><?= $lifeStats->{$category . 'Score'} ?></i></td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
              <div class="col-md-12">
                  <div class="card strpied-tabled-with-hover kills-per-match">
                      <div class="card-header ">
                          <h4 class="card-title">Kills Per Match</h4>
                          <div class="form-check form-check-inline">
                              <label class="form-check-label">
                                  <input class="form-check-input top-one-only" type="checkbox" data-category="<?= $category ?>">
                                  <span class="form-check-sign"></span>
                                  Show only #Top1
                              </label>
                          </div>
                      </div>
                      <div class="card-body">
                          <div class="stats-chart" data-dates="<?= htmlspecialchars(json_encode($result[$category]['dates']), ENT_QUOTES, 'UTF-8') ?>" data-kills='<?= json_encode($result[$category]['kills']) ?>'></div>
                      </div>
                  </div>
              </div>
              <div class="col-md-6">
                  <div class="card strpied-tabled-with-hover">
                      <div class="card-header ">
                          <h4 class="card-title">Kills Repartition</h4>
                      </div>
                      <div class="card-body">
                          <div class="repartition-chart" data-stats='<?= json_encode($result[$category]['repartition']['kills']) ?>'></div>
                      </div>
                  </div>
              </div>
              <div class="col-md-6">
                  <div class="card strpied-tabled-with-hover">
                      <div class="card-header ">
                          <h4 class="card-title">Top1 Repartition</h4>
                      </div>
                      <div class="card-body">
                          <div class="repartition-chart" data-stats='<?= json_encode($result[$category]['repartition']['top1']) ?>'></div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    <?php endforeach ?>
</div>
